[package]
name = "multinode_integration_tests"
version = "0.4.8"
authors = ["Substratum Developer <substratum@substratum.net>"]
license = "GPL-3.0-only"
copyright = "Copyright (c) 2017-2019, Substratum LLC (https://substratum.net) and/or its affiliates. All rights reserved."
description = ""
edition = "2018"
workspace = "../node"

[dependencies]
base64 = "0.10.0"
pretty-hex = "0.1.0"
regex = "1.0.5"
rustc-hex = "2.0.1"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_cbor = "0.9.0"
sha1 = "0.6.0"
native-tls = "0.2.3"
node = { path = "../node", features = [ "expose_test_privates" ] }

[lib]
name = "multinode_integration_tests_lib"
path = "src/lib.rs"

[[bin]]
name = "mock_node"
path = "src/main.rs"
