[package]
name = "dns_utility"
version = "1.0.0-rc.1"
license = "GPL-3.0-only"
authors = ["Substratum Services"]
copyright = "Copyright (c) 2017-2019, Substratum LLC (https://substratum.net) and/or its affiliates. All rights reserved."
description = "Command-line utility to turn DNS subversion on and off"
edition = "2018"

[dependencies]
regex = "1.0.5"
libc = "0.2.43"
ipconfig = "0.2.1"

[target.'cfg(target_os = "macos")'.dependencies]
system-configuration = "0.1.0"
core-foundation = "0.5.1"

[target.'cfg(target_os = "windows")'.dependencies]
winreg = "0.5.1"

[dev-dependencies]

[[bin]]
name = "dns_utility"
path = "src/main.rs"

[[bin]]
name = "dns_utilityw"
path = "src/main_win.rs"

[lib]
name = "dns_utility_lib"
path = "src/lib.rs"

cargo-bundle = "0.4.0"
