[package]
name = "neighborhood_lib"
version = "0.3.1"
license = "GPL-3.0-only"
authors = ["Substratum Services"]
copyright = "Copyright (c) 2017-2018, Substratum LLC (https://substratum.net) and/or its affiliates. All rights reserved."
workspace = "../node"

[dependencies]
regex = "0.2.3"
sub_lib = { path = "../sub_lib" }
