[package]
name = "node"
version = "0.4.5"
license = "GPL-3.0-only"
authors = ["Substratum Services"]
copyright = "Copyright (c) 2017-2019, Substratum LLC (https://substratum.net) and/or its affiliates. All rights reserved."
description = "SubstratumNode is the foundation of SubstratumNetwork, an open-source network that allows anyone to allocate spare computing resources to make the internet a free and fair place for the entire world."
edition = "2018"

[workspace]
members = ["../multinode_integration_tests"]

[dependencies]
actix = "= 0.7.9"
base64 = "0.10.0"
bytes = "0.4.11"
chrono = "0.4.6"
dirs = "1.0.5"
flexi_logger = "0.10.0"
futures = "0.1.25"
http = "0.1.17"
lazy_static = "1.2.0"
log = "0.4.6"
rand = "0.5.5"
regex = "1.0.5"
pretty-hex = "0.1.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
serde_cbor = "0.9.0"
sha1 = "0.6.0"
tokio = "0.1.15"
tokio-core = "0.1.12"
trust-dns = "0.16.0"
trust-dns-resolver = "0.10.3"
fdlimit = "0.1.1"
clap = "2.33.0"

[dependencies.rusqlite]
version = "0.18.0"
features = ["bundled"]

[dependencies.web3]
version = "0.6.0"
default-features = false
features = ["http", "tls"]

[dependencies.websocket]
version = "0.22.1"
default-features = false
features = ["async", "sync"]

[dev-dependencies]
native-tls = "0.2.3"
trust-dns-proto = "0.4.0"
simple-server = "0.4.0"
serial_test_derive = "0.2.0"
serial_test = "0.2.0"

[target.'cfg(unix)'.dependencies]
daemonize = "0.3.0"

[target.'cfg(not(windows))'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[target.'cfg(windows)'.dependencies]

[[bin]]
name = "SubstratumNode"
path = "src/main.rs"

[lib]
name = "node_lib"
path = "src/lib.rs"

cargo-bundle = "0.4.0"
