[package]
name = "node"
version = "0.4.8"
license = "GPL-3.0-only"
authors = ["Substratum Services"]
copyright = "Copyright (c) 2017-2019, Substratum LLC (https://substratum.net) and/or its affiliates. All rights reserved."
description = "SubstratumNode is the foundation of SubstratumNetwork, an open-source network that allows anyone to allocate spare computing resources to make the internet a free and fair place for the entire world."
edition = "2018"

[workspace]
members = ["../multinode_integration_tests"]

[dependencies]
actix = "= 0.7.9"
base64 = "0.10.0"
bytes = "0.4.12"
chrono = "0.4.6"
clap = "2.33.0"
dirs = "2.0.1"
ethsign-crypto = "0.1.0"
ethereum-types = "0.6.0"
fdlimit = "0.1.1"
flexi_logger = "0.13.2"
futures = "0.1.25"
http = "0.1.17"
indoc = "0.3"
itertools = "0.8.0"
lazy_static = "1.2.0"
libsecp256k1 = "0.2.2"
log = "0.4.6"
pretty-hex = "0.1.0"
rand = "0.5.5"
regex = "1.0.5"
rlp = "0.4.0"
rpassword = "3.0.2"
rustc-hex = "2.0.1"
serde = "1.0.94"
serde_derive = "1.0.94"
serde_json = "1.0.40"
serde_cbor = "0.10.0"
sha1 = "0.6.0"
sodiumoxide = "0.2.2"
tiny-bip39 = "0.6.2"
tiny-hderive = "0.2.1"
tokio = "0.1.15"
tokio-core = "0.1.12"
toml = "0.5.1"
trust-dns = "0.16.0"
trust-dns-resolver = "0.10.3"

[dependencies.ethsign]
version = "0.6.1"
default-features = false
features = ["pure-rust"]

[dependencies.primitive-types]
version = "0.4.0"
default-features = false
features = ["default", "rlp", "serde"]

[dependencies.rusqlite]
version = "0.18.0"
features = ["bundled"]

[dependencies.web3]
version = "0.7.0"
default-features = false
features = ["http", "tls"]

[dependencies.websocket]
version = "0.22.4"
default-features = false
features = ["async", "sync"]

[dev-dependencies]
base58 = "0.1.0"
native-tls = {features = ["vendored"], version = "0.2.3"}
simple-server = "0.4.0"
serial_test_derive = "0.2.0"
serial_test = "0.2.0"
trust-dns-proto = "0.4.0"
jsonrpc-core = "11.0.0"

[target.'cfg(unix)'.dependencies]
daemonize = "0.3.0"

[target.'cfg(not(windows))'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[target.'cfg(windows)'.dependencies]

[[bin]]
name = "SubstratumNode"
path = "src/main.rs"

[[bin]]
name = "SubstratumNodeW"
path = "src/main_win.rs"

[lib]
name = "node_lib"
path = "src/lib.rs"

cargo-bundle = "0.4.0"

[features]
expose_test_privates = []
