[package]
name = "proxy_client_lib"
version = "0.3.5"
license = "GPL-3.0-only"
authors = ["Substratum Services"]
copyright = "Copyright (c) 2017-2018, Substratum LLC (https://substratum.net) and/or its affiliates. All rights reserved."
workspace = "../node"

[dependencies]
actix = "0.5.7"
futures = "0.1.20"
serde_cbor = "0.8.1"
tokio = "0.1.7"
tokio-core = "0.1.12"
trust-dns-proto = "0.3.2"
trust-dns-resolver = "0.8.1"
sub_lib = { path = "../sub_lib" }

[dev-dependencies]
test_utils = { path = "../test_utils" }

[lib]
name = "proxy_client_lib"
path = "src/lib.rs"
