[package]
name = "proxy_client_lib"
version = "0.1.0"
license = "GPL-3.0-only"
authors = ["Substratum Services"]
copyright = "Copyright (c) 2017-2018, Substratum LLC (https://substratum.net) and/or its affiliates. All rights reserved."

[dependencies]
trust-dns-resolver = "0.8.1"
sub_lib = { path = "../sub_lib" }
serde_cbor = "0.8.1"

[lib]
name = "proxy_client_lib"
path = "src/lib.rs"
